# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 9b6c2d9ef9f646f7fba60192efda00ae67efb2f2fce976f4fe4768152312dce588c888c92500e2154cdb2d0f6368d41e0c1bbbf31ee30cb57fc49fe4cf814823

test:
  secret_key_base: 67fbac74637813defdc7c722eab653be67cac785c28381db393af4dec9b5da9be930bbba66da856f27e1b6a53bc4a0ebfe0d0e36e8307a5caf58cdb976151860

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
